In [6]:
import os
import numpy as np
import xarray as xr
import pandas as pd
import netCDF4 as nc
import geopandas as gpd
import rioxarray as rxr
from myfunc import timer
from myfunc import DirMan
from myfunc import load_and_flatten_data
import config

# configuration
# resolution = "0p1"
resolution = "500"
region = [-180,180,-60,90]
# region = [-124.8,-66.95,24.5,49.4]
data_path = f'/tera04/zhwei/xionghui/bedrock/run/{resolution}/'
post_data_path = '/tera04/zhwei/xionghui/bedrock/'
shp_path = '/tera04/zhwei/xionghui/bedrock/Shp/'
fig_path = f'/home/xuxh22/stu01/Bedrock/fig/{resolution}/'
path = '/home/xuxh22/stu01/Bedrock/'
if resolution == "0p1":
    size = 0.1
elif resolution == "500":
    size = 0.0005

dir_man = DirMan(data_path)
dir_man.enter()

os.makedirs(f'{data_path}/csv', exist_ok=True)

casename1 = 'bedrock_1'
path1 = f'{data_path}/cases/{casename1}/'
casename2 = 'bedrock_2'
path2 = f'{data_path}/cases/{casename2}/'
casename3 = 'bedrock_3'
path3 = f'{data_path}/cases/{casename3}/'

Entered /tera04/zhwei/xionghui/bedrock/run/500/

In [2]:
df = pd.DataFrame()

with nc.Dataset(f'Sbedrock.nc4') as dataset:
    lat = dataset['lat'][:].flatten()
    lon = dataset['lon'][:].flatten()
    df['lat'] = np.repeat(lat, len(lon))
    df['lon'] = np.tile(lon, len(lat))

file_variable_list = [
    (f'mask1234', 'Band1'),
    # (f'Sbedrock', 'Sbedrock'),
    (f'Sbedrock', 'Band1'),
    (f'Area', 'area'),

    (f'{path1}Sbedrock_mean', 'Sr'),
    (f'{path2}Sbedrock_mean', 'Sr'),
    (f'{path3}Sbedrock_mean', 'Sr'),
]

for entry in file_variable_list:
    file = entry[0]
    variable_name = entry[1]  
    index = entry[2:] if len(entry) > 2 else None  

    # print(f"File: {file}, Variable: {variable_name}, Index: {index}")
    if index:
        df[file] = load_and_flatten_data(file, variable_name, index[0])
    else:
        df[file] = load_and_flatten_data(file, variable_name)


# df = df.dropna()
# df = df[df['Sbedrock'] > 0]
df = df[df['mask1234'] == 1]
df.drop(labels='mask1234',axis=1,inplace=True)

print(df[f'{path1}Sbedrock_mean'].mean())
print(df[f'{path2}Sbedrock_mean'].mean())
print(df[f'{path3}Sbedrock_mean'].mean())
print(df['Sbedrock'].mean())

with open(f'csv/Global_cases_sb.csv','w') as f:
    df.to_csv(f)
df

129.20021
27.280539
66.86907
100.01836

,lat,lon,Sbedrock,Area,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_1/Sbedrock_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_2/Sbedrock_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_3/Sbedrock_mean
708161369,-55.847917,-67.627083,0.236460,120515.621801,NaN,NaN,NaN
708161370,-55.847917,-67.622916,0.279453,120515.621801,NaN,NaN,NaN
708161371,-55.847917,-67.618749,0.322446,120515.621801,NaN,NaN,NaN
708161372,-55.847917,-67.614583,0.365440,120515.621801,NaN,NaN,NaN
708161373,-55.847917,-67.610416,0.408433,120515.621801,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3586500782,82.960414,-26.739583,39.301605,26309.225697,NaN,NaN,NaN
3586500783,82.960414,-26.735417,39.884819,26309.225697,NaN,NaN,NaN
3586500784,82.960414,-26.731250,40.468037,26309.225697,NaN,NaN,NaN
3586500785,82.960414,-26.727083,41.051250,26309.225697,NaN,NaN,NaN
3586500786,82.960414,-26.722917,41.634464,26309.225697,NaN,NaN,NaN

In [3]:
df = pd.DataFrame()

with nc.Dataset(f'Sbedrock.nc4') as dataset:
    lat = dataset['lat'][:].flatten()
    lon = dataset['lon'][:].flatten()
    df['lat'] = np.repeat(lat, len(lon))
    df['lon'] = np.tile(lon, len(lat))

file_variable_list = [
    (f'mask1234', 'Band1'),
    (f'Area', 'area'),

    (f'{path1}Ssoil_mean', 'Sr'),
    (f'{path2}Ssoil_mean', 'Sr'),
    (f'{path3}Ssoil_mean', 'Sr'),
    (f'Ssoil', 'Band1'),
]

for entry in file_variable_list:
    file = entry[0]
    variable_name = entry[1]  
    index = entry[2:] if len(entry) > 2 else None  
    if index:
        df[file] = load_and_flatten_data(file, variable_name, index[0])
    else:
        df[file] = load_and_flatten_data(file, variable_name)


# df = df.dropna()
# df = df[df['Sbedrock'] > 0]
df = df[df['mask1234'] == 1]
df.drop(labels='mask1234',axis=1,inplace=True)

print(df[f'{path1}Ssoil_mean'].mean())
print(df[f'{path2}Ssoil_mean'].mean())
print(df[f'{path3}Ssoil_mean'].mean())
print(df['Ssoil'].mean())

with open(f'csv/Global_cases_ss.csv','w') as f:
    df.to_csv(f)
df

191.27011
123.12878
143.0852
95.06395

,lat,lon,Area,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_1/Ssoil_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_2/Ssoil_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_3/Ssoil_mean,Ssoil
708161369,-55.847917,-67.627083,120515.621801,NaN,NaN,NaN,124.583191
708161370,-55.847917,-67.622916,120515.621801,NaN,NaN,NaN,125.309280
708161371,-55.847917,-67.618749,120515.621801,NaN,NaN,NaN,126.056290
708161372,-55.847917,-67.614583,120515.621801,NaN,NaN,NaN,0.000000
708161373,-55.847917,-67.610416,120515.621801,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...
3586500782,82.960414,-26.739583,26309.225697,0.0,0.0,0.0,0.000000
3586500783,82.960414,-26.735417,26309.225697,0.0,0.0,0.0,0.000000
3586500784,82.960414,-26.731250,26309.225697,0.0,0.0,0.0,0.000000
3586500785,82.960414,-26.727083,26309.225697,0.0,0.0,0.0,0.000000
3586500786,82.960414,-26.722917,26309.225697,0.0,0.0,0.0,0.000000

In [ ]:
df = pd.DataFrame()

with nc.Dataset(f'Sbedrock.nc4') as dataset:
    lat = dataset['lat'][:].flatten()
    lon = dataset['lon'][:].flatten()
    df['lat'] = np.repeat(lat, len(lon))
    df['lon'] = np.tile(lon, len(lat))

file_variable_list = [
    (f'mask1234', 'Band1'),
    (f'Area', 'area'),

    (f'{path1}Sr_mean', 'Sr'),
    (f'{path2}Sr_mean', 'Sr'),
    (f'{path3}Sr_mean', 'Sr'),
    # (f'Sr', 'Sr'),
    (f'Sr', 'Band1'),
]

for entry in file_variable_list:
    file = entry[0]
    variable_name = entry[1]  
    index = entry[2:] if len(entry) > 2 else None  
    if index:
        df[file] = load_and_flatten_data(file, variable_name, index[0])
    else:
        df[file] = load_and_flatten_data(file, variable_name)


# df = df.dropna()
# df = df[df['Sbedrock'] > 0]
df = df[df['mask1234'] == 1]
df.drop(labels='mask1234',axis=1,inplace=True)

print(df[f'{path1}Sr_mean'].mean())
print(df[f'{path2}Sr_mean'].mean())
print(df[f'{path3}Sr_mean'].mean())
print(df['Sr'].mean())

with open(f'csv/Global_cases_sr.csv','w') as f:
    df.to_csv(f)
df

324.29422
156.02934
214.27704
197.01656

,lat,lon,Area,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_1/Sr_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_2/Sr_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_3/Sr_mean,Sr
708161369,-55.847917,-67.627083,120515.621801,NaN,NaN,NaN,0.236460
708161370,-55.847917,-67.622916,120515.621801,NaN,NaN,NaN,0.279453
708161371,-55.847917,-67.618749,120515.621801,NaN,NaN,NaN,0.322446
708161372,-55.847917,-67.614583,120515.621801,NaN,NaN,NaN,0.365440
708161373,-55.847917,-67.610416,120515.621801,NaN,NaN,NaN,0.408433
...,...,...,...,...,...,...,...
3586500782,82.960414,-26.739583,26309.225697,NaN,NaN,NaN,39.301605
3586500783,82.960414,-26.735417,26309.225697,NaN,NaN,NaN,39.884819
3586500784,82.960414,-26.731250,26309.225697,NaN,NaN,NaN,40.468037
3586500785,82.960414,-26.727083,26309.225697,NaN,NaN,NaN,41.051250
3586500786,82.960414,-26.722917,26309.225697,NaN,NaN,NaN,41.634464

:

In [7]:
df = pd.DataFrame()

with nc.Dataset(f'Sbedrock.nc4') as dataset:
    lat = dataset['lat'][:].flatten()
    lon = dataset['lon'][:].flatten()
    df['lat'] = np.repeat(lat, len(lon))
    df['lon'] = np.tile(lon, len(lat))

file_variable_list = [
    (f'mask1234', 'Band1'),
    (f'Area', 'area'),

    (f'{path1}rnof_mean', 'f_rnof'),
    (f'{path2}rnof_mean', 'f_rnof'),
    (f'{path3}rnof_mean', 'f_rnof'),

    (f'{path1}fevpa_mean', 'f_fevpa'),
    (f'{path2}fevpa_mean', 'f_fevpa'),
    (f'{path3}fevpa_mean', 'f_fevpa'),
    # (f'Q_mean', 'tp', 0),
    # (f'ET_mean', 'et', 0),
]

for entry in file_variable_list:
    file = entry[0]
    variable_name = entry[1]  
    index = entry[2:] if len(entry) > 2 else None  

    # print(f"File: {file}, Variable: {variable_name}, Index: {index}")
    if index:
        df[file] = load_and_flatten_data(file, variable_name, index[0])
    else:
        df[file] = load_and_flatten_data(file, variable_name)


# df = df.dropna()
# df = df[df['Sbedrock'] > 0]
df = df[df['mask1234'] == 1]
df.drop(labels='mask1234',axis=1,inplace=True)

print(df[f'{path1}rnof_mean'].mean())
print(df[f'{path2}rnof_mean'].mean())
print(df[f'{path3}rnof_mean'].mean())
print(df[f'{path1}fevpa_mean'].mean())
print(df[f'{path2}fevpa_mean'].mean())
print(df[f'{path3}fevpa_mean'].mean())
# print(df['Q_mean'].mean())
# print(df['ET_mean'].mean())

with open(f'csv/Global_cases_runoff_et.csv','w') as f:
    df.to_csv(f)
df

202.67711
441.20398
214.47939
627.292
501.03973
602.17175

,lat,lon,Area,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_1/rnof_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_2/rnof_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_3/rnof_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_1/fevpa_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_2/fevpa_mean,/tera04/zhwei/xionghui/bedrock/run/500//cases/bedrock_3/fevpa_mean
708161369,-55.847917,-67.627083,120515.621801,74.590279,137.660324,56.517910,217.021515,190.206039,216.607361
708161370,-55.847917,-67.622916,120515.621801,88.147781,162.681412,66.790581,256.467255,224.777817,255.977829
708161371,-55.847917,-67.618749,120515.621801,101.705276,187.702484,77.063255,295.912994,259.349579,295.348297
708161372,-55.847917,-67.614583,120515.621801,115.262779,212.723572,87.335930,335.358734,293.921356,334.718781
708161373,-55.847917,-67.610416,120515.621801,128.820282,237.744659,97.608604,374.804504,328.493134,374.089233
...,...,...,...,...,...,...,...,...,...
3586500782,82.960414,-26.739583,26309.225697,10.514077,10.773910,10.624814,6.449410,6.217391,6.365170
3586500783,82.960414,-26.735417,26309.225697,14.716483,15.080170,14.871482,9.027196,8.702441,8.909286
3586500784,82.960414,-26.731250,26309.225697,18.918890,19.386429,19.118149,11.604982,11.187490,11.453403
3586500785,82.960414,-26.727083,26309.225697,23.121296,23.692688,23.364817,14.182768,13.672540,13.997519
3586500786,82.960414,-26.722917,26309.225697,27.323702,27.998949,27.611483,16.760553,16.157589,16.541636

In [ ]:
# df = pd.read_csv(f'/tera04/zhwei/xionghui/bedrock/run/{resolution}/csv/Global_cases_runoff_et.csv')
# print(df[f'{path1}rnof_mean'].mean())
# print(df[f'{path2}rnof_mean'].mean())
# print(df[f'{path3}rnof_mean'].mean())
# print(df[f'{path1}fevpa_mean'].mean())
# print(df[f'{path2}fevpa_mean'].mean())
# print(df[f'{path3}fevpa_mean'].mean())